### ISSUE TITLE
markdown mixed with latex, alternative separators

### ISSUE THREAD

**Issue by Netsaver** [markdown-it/markdown-it-sup#2]
Hi, I'm using a Tiddlywiki's plugin for markdown (_Anstosa_'s one), which I mix with latex, based on _markdown-it_ (a part from a wrapper calling markdown-it modules, all these modules are original).
Well, unfortunately **markdown-it sup and sub plugins seem to be incompatible with latex code** as `^` and `_` symbols are used for a similar purpose in equations:
`${ (A^p)^{-1} = (AA^{p-1})^{-1} =...` rendering this way: **(A<sup>p)</sup>= (AA<sup>{p-1})</sup>=**.  
So the question is: is it possible to change **sup** and **sub** delimiters, e.g. doubling them, as in:
`H__2__0`, `a^^2^^ + b^^2^^=c^^2^^` ? 
Thanks and regards,
Paul Netsaver, Rome

**Comment by puzrin** [comment]
I'm not sure that understand your question. If you propose to change defaults, answer is "no", because current markup is well known convention. If you wish to have customized version - nobody can prohibit you to do so.

Also, probably your latex plugin should be fixed to not allow markdown markup inside. See [this example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60foo%5Ebar%5E%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). `^` inside inlined code block is ok.

**Comment by Netsaver** [comment]
I also think that best solution would be inhibit markdown inside latex code. 
The point is that latex plugin does not lies on markdown, but on a third environment not including markdown.
So latex was one of the first plugins and markdown followed later (one of the last is markdown-it based).
I don't know the sequence, but I suppose markdown parsing is applied before latex, so I think markdown plugin should be adapted to avoid latex delimited sections.
Thanks anyway.
