### ISSUE TITLE
whitespace breaks "sup" parsing

### ISSUE THREAD

**Issue by dajare** [markdown-it/markdown-it-sup#3]
I see from the README that "nested markup is currently not supported" (also on [markdown-it-sub][1]). But it did surprise me that "whitespace" breaks the parsing:

- `^up^` = <sup>up</sup>
- `^up.up^` = <sup>up.up</sup>

But with  `tab` or `space`, the superscript fails. I see this:

- `^up&tab;up^` = ^up	up^
- `^up&#x20;up^` = ^up up^

\[That last example with `space` (U+0020) of course. I haven't tested other kinds of "[whitespace][w]".\]

Is this by design? It seems counter-intuitive if `markdown-it-sup` is extending the feature set by adding `<sup>...</sup>` equivalence. (And it seems the same is also true of `markdown-it-sub`, but I haven't posted this there.)

[1]: https://github.com/markdown-it/markdown-it-sub
[w]: https://en.wikipedia.org/wiki/Whitespace_character

**Comment by puzrin** [comment]
Yes, it's by design, because official spec not exists and nobody knows how it should work (too many collisions possible).

Workaround is to use escaping via backslash: [`^up\ up^`](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%5Eup%5C%5C%20up%5E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Consider sub/sup as "something simplified you can use without guarantees".

**Comment by dajare** [comment]
Thanks for that helpful (and quick!) reply. So this will be a sensible "won't fix", but good to have the workaround documented. 

And that "consideration" makes good sense to me! Thanks again.

**Comment by puzrin** [comment]
You can make PR if you wish. I don't remember details about addons after those landed.

Also, can try to ping sub/sup spec actrivity on commonmark forum (but, to be honest, i don't beleive it helps in reasonable future).
